"""Add game_user Association Table addend

Revision ID: 62d6e81c84a1
Revises: 9b9de8219b80
Create Date: 2024-02-13 09:20:11.639165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d6e81c84a1'
down_revision = '9b9de8219b80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
